<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_LOGIN</name>
   <tag></tag>
   <elementGuidId>d1a343fc-e675-4dd0-bb9f-61aa02fd9e65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>63a512e3-610d-41eb-9e5e-97dd44d2978a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-5 tracking-wide font-semibold bg-custom-blue text-gray-100 w-full py-4 rounded-lg hover:bg-custom-hover-blue transition-all duration-300 ease-in-out flex items-center justify-center focus:shadow-outline focus:outline-none</value>
      <webElementGuid>fbcf1ad0-5fd5-4539-86d5-6fe672e1f6d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d2761622-3681-4d77-a101-c8a713ce4ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LOGIN</value>
      <webElementGuid>78cf1a83-5c6f-45f8-b729-1c80b4a59230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;min-h-screen bg-gray-100 text-gray-900 flex justify-center __className_e53722&quot;]/div[@class=&quot;max-w-screen-xl m-0 sm:m-20 bg-white shadow-sm rounded-2xl flex justify-center flex-1&quot;]/div[@class=&quot;py-16&quot;]/div[@class=&quot;mt-12 flex flex-col justify-between items-center&quot;]/div[@class=&quot;w-full flex-1&quot;]/div[@class=&quot;mx-auto max-w-xs&quot;]/form[1]/button[@class=&quot;mt-5 tracking-wide font-semibold bg-custom-blue text-gray-100 w-full py-4 rounded-lg hover:bg-custom-hover-blue transition-all duration-300 ease-in-out flex items-center justify-center focus:shadow-outline focus:outline-none&quot;]</value>
      <webElementGuid>a825ce90-9620-4022-b2b7-6f60b1f3e772</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>083abe34-0cf5-4b86-920d-7d3e26081dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div/div[2]/div[2]/div/form/button</value>
      <webElementGuid>42a9b07c-6e1a-46c9-9781-bf586ec03bec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[1]</value>
      <webElementGuid>864a8fc8-92e6-4c47-90b0-3e51a93e2090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/following::button[1]</value>
      <webElementGuid>a79d5b6b-92c7-4e77-b5aa-0b785d645cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2025 | Dinas Pendidikan Jawa Barat'])[1]/preceding::button[1]</value>
      <webElementGuid>13282359-8bd9-49bf-b4b9-f255ef129eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LOGIN']/parent::*</value>
      <webElementGuid>7c11efb6-9d26-4a2e-b914-fe3e46c6f184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>6d64ebf4-4834-44ae-877f-8f27f53f8adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'LOGIN' or . = 'LOGIN')]</value>
      <webElementGuid>269338bd-f6c4-43a3-9880-91659b56fab1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
